use std::io::Write;

fn main() {
    let out_dir = format!("{}/protos", std::env::var("OUT_DIR").unwrap());

    std::fs::create_dir_all(&out_dir).unwrap();

    protobuf_codegen::Codegen::new()
        .pure()
        .out_dir(out_dir)
        .inputs(["protos/rendezvous.proto", "protos/message.proto"])
        .include("protos")
        .customize(protobuf_codegen::Customize::default().tokio_bytes(true))
        .run()
        .expect("Codegen failed.");

    gen_bgdesk_config();
}

fn gen_bgdesk_config() {
    use std::io::Write;
    use std::path::PathBuf;

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let settings_path = manifest_dir.join("../../config/settings.toml");

    println!("cargo:rerun-if-changed={}", settings_path.display());

    let content = std::fs::read_to_string(&settings_path).unwrap_or_else(|_| {
        panic!(
            "config/settings.toml not found at {}.\n\
             Initialize the config submodule: git submodule update --init config",
            settings_path.display()
        )
    });

    let settings: toml::Table = content.parse().expect("invalid config/settings.toml");

    let is_debug = std::env::var("PROFILE").unwrap_or_default() == "debug";

    let mut rendezvous_server = required_string(&settings, "rendezvous_server");
    if is_debug {
        rendezvous_server = "127.0.0.1".to_owned();
    }
    let api_server = required_string(&settings, "api_server");
    let version_check_url = required_string(&settings, "version_check_url");
    let rs_pub_key = required_string(&settings, "rs_pub_key");
    let link_docs_home = required_string(&settings, "link_docs_home");
    let link_docs_x11_required = required_string(&settings, "link_docs_x11_required");
    let link_headless_linux_support = required_string(&settings, "link_headless_linux_support");

    let defaults = required_table(&settings, "defaults");
    let hard = required_table(&settings, "hard");
    let builtin = required_table(&settings, "builtin");

    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("bgdesk_config.rs");
    let mut file = std::fs::File::create(&out_path).expect("create bgdesk_config.rs");

    writeln!(
        file,
        "// @generated by build.rs from config/settings.toml — DO NOT EDIT"
    )
    .unwrap();
    writeln!(
        file,
        "pub const RENDEZVOUS_SERVERS: &[&str] = &[\"{}\"];",
        escape(&rendezvous_server)
    )
    .unwrap();
    writeln!(
        file,
        "pub const RS_PUB_KEY: &str = \"{}\";",
        escape(&rs_pub_key)
    )
    .unwrap();
    writeln!(
        file,
        "pub const API_SERVER: &str = \"{}\";",
        escape(api_server)
    )
    .unwrap();
    writeln!(
        file,
        "pub const VERSION_CHECK_URL: &str = \"{}\";",
        escape(version_check_url)
    )
    .unwrap();
    writeln!(
        file,
        "pub const LINK_DOCS_HOME: &str = \"{}\";",
        escape(link_docs_home)
    )
    .unwrap();
    writeln!(
        file,
        "pub const LINK_DOCS_X11_REQUIRED: &str = \"{}\";",
        escape(link_docs_x11_required)
    )
    .unwrap();
    writeln!(
        file,
        "pub const LINK_HEADLESS_LINUX_SUPPORT: &str = \"{}\";",
        escape(link_headless_linux_support)
    )
    .unwrap();
    write_default_settings_fn(&mut file, defaults, &rs_pub_key, is_debug)
    .unwrap();
    write_hashmap_fn(&mut file, "bgdesk_hard_settings", hard).unwrap();
    write_hashmap_fn(&mut file, "bgdesk_builtin_settings", builtin).unwrap();
}

fn required_string(table: &toml::Table, key: &str) -> String {
    table
        .get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("config/settings.toml: missing or invalid `{key}`"))
        .to_owned()
}

fn required_table<'a>(table: &'a toml::Table, key: &str) -> &'a toml::Table {
    table
        .get(key)
        .and_then(|v| v.as_table())
        .unwrap_or_else(|| panic!("config/settings.toml: missing or invalid `[{key}]`"))
}

fn escape(value: impl AsRef<str>) -> String {
    value
        .as_ref()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}

fn write_default_settings_fn(
    file: &mut std::fs::File,
    table: &toml::Table,
    rs_pub_key: &str,
    is_debug: bool,
) -> std::io::Result<()> {
    let default_key = rs_pub_key;
    let mut entries: Vec<(String, String)> = table
        .iter()
        .filter_map(|(key, value)| {
            let value = value.as_str().unwrap_or_else(|| {
                panic!("config/settings.toml: `[defaults]` key `{key}` must be a string")
            });
            Some((key.clone(), value.to_owned()))
        })
        .collect();
    for (key, value) in &mut entries {
        if key == "key" {
            *value = default_key.to_owned();
        } else if is_debug && key == "custom-rendezvous-server" {
            *value = "127.0.0.1".to_owned();
        }
    }
    writeln!(file, "pub fn bgdesk_default_settings() -> HashMap<String, String> {{")?;
    writeln!(file, "    HashMap::from([")?;
    for (idx, (key, value)) in entries.iter().enumerate() {
        let comma = if idx + 1 == entries.len() { "" } else { "," };
        writeln!(
            file,
            "        (\"{}\".to_string(), \"{}\".to_string()){comma}",
            escape(key),
            escape(value)
        )?;
    }
    writeln!(file, "    ])")?;
    writeln!(file, "}}")?;
    Ok(())
}

fn write_hashmap_fn(
    file: &mut std::fs::File,
    fn_name: &str,
    table: &toml::Table,
) -> std::io::Result<()> {
    writeln!(file, "pub fn {fn_name}() -> HashMap<String, String> {{")?;
    writeln!(file, "    HashMap::from([")?;
    for (idx, (key, value)) in table.iter().enumerate() {
        let value = value
            .as_str()
            .unwrap_or_else(|| panic!("config/settings.toml: `[{fn_name}]` key `{key}` must be a string"));
        let comma = if idx + 1 == table.len() { "" } else { "," };
        writeln!(
            file,
            "        (\"{}\".to_string(), \"{}\".to_string()){comma}",
            escape(key),
            escape(value)
        )?;
    }
    writeln!(file, "    ])")?;
    writeln!(file, "}}")?;
    Ok(())
}
